Feature/initial skeleton dock compose
CartoDB/carto3-helm pull request #7
Opened 2021-11-25 17:04 UTC by randradas

**Description of the change**

This is a very initial docker-compose skeleton used to figure out how the Carto docker-compose.yaml would be. It helps to know how the nodejs container works which will be used to run Carto app.

This docker-compose uses fake images to run a Hello world application with node and also serve an static imagen which are bot things that need to be done to run Carto. Finally it is worth to mention that either the docker-compose file and the nginx.conf file are intentionally similar to the one provided by Carto.

**Benefits**

Helps to understand the architecture and can be used as sandbox to try some possible configurations.

2021-11-26 08:56 UTC, javsalgar requested changes

2021-11-26 08:56 UTC, javsalgar commented on docker/docker-compose.yaml
> +    command: sh -c 'npm install && npm start'
As the volume is shared between multiple applications, there could be issues with running multiple npm installs in parallel. Wouldn't it make more sense to change it to a `build: .` approach and create an image with the fake application?

2021-11-26 08:56 UTC, javsalgar commented on docker/docker-compose.yaml
> +      - POSTGRESQL_PASSWORD=
This line should not be necessary

2021-11-30 17:07 UTC, randradas commented on docker/docker-compose.yaml
> +    command: sh -c 'npm install && npm start'
You are right, please let me explain the contest. Since this is just fake and the goal was to write a Carto-ish docker-compose file able to get node based container up I have push a commit that uses separate volumes, it is not clean enough but it is just a proof of concept docker-compose.yaml that I wrote while the actual Carto containers were not available to me due to legal paperwork in progress.

In the following commits in other PRs there will a better approach docker-compose that uses images that contains the application built-in and where volumes are not used (not persistence needed). Thank you so much for your feedback, it is useful, I didn't realize the volumes were being shared ;).

2021-11-30 17:40 UTC, javsalgar approved these changes

2021-12-01 08:59 UTC, merged